# Generated by Django 6.0.2 on 2026-02-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_project_is_completed_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('Planning', 'Planning'), ('Designing', 'Designing'), ('Development', 'Development'), ('Testing', 'Testing'), ('Deployed', 'Deployed')], default='Planning', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='resource_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
