# Generated by Django 6.0.2 on 2026-02-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_expense_project_phase_project_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='resource_link',
        ),
        migrations.AddField(
            model_name='project',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
