# Generated by Django 6.0.2 on 2026-02-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_project_resource_link_project_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expense_history',
            field=models.TextField(blank=True, default=''),
        ),
    ]
